### ISSUE TITLE
No wwwroot directory in backend

### ISSUE THREAD

**Issue by ElaAlex** [mdymel/AspNetCoreAngular2Cli#2]
First of all: great work - I'd love to have a seed project like this!

Now to my question: I downloaded the repo and ran npm start -> Everything works perfectly. When I run npm build there's also no error but I can't find the output. There's not even an wwwroot directory within the whole solution. Do you have any ideas?

**Comment by mdymel** [comment]
Hi,
thanks - glad you find it helpful :) 

There is a corresponding [blog post](https://devblog.dymel.pl/2016/10/25/angular2-cli-with-aspnet-core-application-tutorial/) on my blog. 

You should use `ng build` command to build the project. It should create `wwwroot` directory in the Backend folder.

**Comment by ElaAlex** [comment]
I ran ng build but nothing happened... The solution is simple - I just had to create the wwwroot manually and then everything works. 

Thanks for your help!
